# Session 5: From Single to Multiple Values: Arrays and NumPy

## Overview
This tutorial builds on your knowledge of variables, assignments, and functions by introducing arrays and the NumPy library in Python. By the end of this session, you will understand how to create and manipulate arrays, perform operations on multiple arrays, and use NumPy functions for efficient calculations.

## Prerequisites
- Basic understanding of Python variables, data types, and functions


## Part 1: Introduction to NumPy (20 minutes)

### What is NumPy?
- NumPy is a powerful library for numerical computing in Python.
- It provides support for arrays and matrices, along with a collection of mathematical functions to operate on them.


### Creating Arrays
In Python, arrays can be created manually.

#### Example: Creating an array manually


In [6]:
import numpy as np # first try without this
my_array = np.array([1, 2, 77, 4, 5])
print(my_array)

[ 1  2 77  4  5]


They can also be created quickly and automatically using NumPy function`linspace` to generate evenly spaced points in an interval: `np.linspace(start, stop, number of points)`

#### Example: Creating arrays using NumPy functions

In [8]:
array2 = np.linspace(0,10,5) # if you know number of points
print(array2)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
array2[[0,1]] = [1,2]
print(array2)

[ 1.   2.   5.   7.5 10. ]


## Part 2: Operations with NumPy (20 minutes)

The real advantage of NumPy is that it speeds up operations by allowing you to do operations on the whole array simultaneously rather than having to loop through and operate on each element one-by-one.

### Using NumPy for Mathematical Operations

#### Example:


In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)  # Output: [11 12 13 14 15]
print(arr * 2)   # Output: [ 2  4  6  8 10]


[11 12 13 14 15]
[ 2  4  6  8 10]


### Practice Problem 1
- Create a NumPy array `my_array` with values `[5, 10, 15, 20, 25]`.
- Multiply each element by 3 and print the result.

#### Solution:


In [172]:
my_array = np.linspace(5,25,5)
print(my_array)
my_array = my_array * 3
print(my_array)

[ 5. 10. 15. 20. 25.]
[15. 30. 45. 60. 75.]


### Example: Array Operations

In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0
print(np.sum(arr))   # Output: 15
print(np.max(arr))   # Output: 5
print(np.min(arr))   # Output: 1


3.0
15
5
1


 ### Practice Problem 2

 Write a function that takes two arrays (they have to be the same size), adds them together, and then returns the mean of the summed array.

In [99]:
def sum_and_average(array1, array2):
    summed_array = array1 + array2
    return np.mean(summed_array)

# test out with two random arrays
array1 = np.random.randint((4))
print(array1)
array2 = np.random.randint((4))
print(array2)
mean_array = sum_and_average(array1, array2)
print(mean_array)

[0.80444522 0.79035473 0.19877578 0.57889226]
[0.93949715 0.61271477 0.49545719 0.82599524]
1.3115330871652564


### Accessing Elements
Elements in an array can be accessed using their index.

#### Example: Indexing


In [120]:
print(my_array[0])  # Output: 1
print(my_array[2])  # Output: 77

1
77


You can also access multiple elements at once using multiple indices.

### Example:

In [124]:
print(my_array[0:2])

[ 1 10]


### Modifying Elements
You can modify elements in an array by assigning new values to specific indices.

#### Example:


In [122]:
my_array[1] = 10
print(my_array)  # Output: [1, 10, 77, 4, 5]


[ 1 10 77  4  5]


### Practice Problem 3
- Create an array of numbers with the values `[10, 20, 30, 40, 50]`.
- Change the second element to 25.
- Print the modified array.

#### Solution:


In [126]:
numbers = np.linspace(10,50,5)
print(numbers)
numbers[1] = 25
print(numbers)  # Output: [10, 25, 30, 40, 50]


[10. 20. 30. 40. 50.]
[10. 25. 30. 40. 50.]


### 2D Arrays

You can also make 2D (or higher dimensional, but we'll stick to 2D for now) arrays, which you can think of as tables, with rows and columns. Indexing in 2D arrays thus involves specifying which rows and columns you want. Indexing in a 2D array looks like `2D_array[row, column]`.

#### Example: Creating and slicing a 2D array

In [130]:
# An easy way of creating 2D arrays is making an array of zeros
arr_2D = np.zeros((3,3))
print(arr_2D)
print()

# Access an element
arr_2D[0,2] = 3
print(arr_2D)
print()

# Set a whole row equal to 1
arr_2D[1,:] = 1
print(arr_2D)
print()

# Set a column equal to 2
arr_2D[:,0] = 2
print(arr_2D)
print()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 3.]
 [1. 1. 1.]
 [0. 0. 0.]]

[[2. 0. 3.]
 [2. 1. 1.]
 [2. 0. 0.]]



### Practice Problem 4

Create a 6 by 10 (6 rows and 10 columns) 2D numpy array in which the first row is all 1's, the rest of the second column is all 5's, and the rest of the array is all 0's.

### Solution:

In [139]:
array = np.zeros((6,10))
array[:,1] = 5
array[0,:] = 1
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Part 3: Manipulating Arrays (20 minutes)

### Boolean Indexing
NumPy allows you to quickly access elements of arrays that satisfy a certain condition through boolean indexing.

#### Example:


In [54]:
array = np.arange(0,10)
print(array)

boolean_array = array > 5
print(boolean_array)

cool_array = array[boolean_array]
print(cool_array)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[6 7 8 9]


### Practice Problem 5

Write a function that takes an array and a threshold number, and returns just the values that are greater than that threshold. 

In [159]:
random_array = np.random.rand(5) # creates an array of random values between 0 and 1
print(random_array)

[0.31745358 0.24219495 0.82617009 0.48692649 0.24529277]


## Solution:

In [142]:
def greater_array(array, threshold):
    greater_boolean = array > threshold
    array = array[greater_boolean]
    return array

# test out with an array of random numbers 
greater_random_array = greater_array(random_array, 0.5)
print(greater_random_array)

[0.51107359 0.47729947 0.91419432 0.4763223  0.18280898]
[0.51107359 0.91419432]


## Conclusion and Q&A (10 minutes)
- Review the key concepts covered: creating, indexing in and modifying arrays, element-wise operations, 2D arrays, Booleans arrays and conditional indexing, and using NumPy functions for calculations.
- Encourage practice and experimentation.
- Open the floor for any questions and further clarifications.
